walmartlabs/lacinia-pedestal

CHANGELOG.md
README.md
dev-resources/com/walmartlabs/lacinia/test_utils.clj
dev-resources/logback.xml
project.clj
src/com/walmartlabs/lacinia/pedestal.clj
test/com/walmartlabs/lacinia/async_test.clj
test/com/walmartlabs/lacinia/pedestal_test.clj

Adds support for executing the query asynchronously.
In addition, this adds a new interceptor for setting the application context when executing the query; this makes it easier to customize that behavior while still using the default query executor handler.

Enable async execution of the query

---

src/com/walmartlabs/lacinia/pedestal.clj

Fixes documentation mentioned in issue #7.

Corrects docs for `pedestal-service` & graphiql

---

CHANGELOG.md
README.md
project.clj
src/com/walmartlabs/lacinia/async.clj
src/com/walmartlabs/lacinia/pedestal.clj
test/com/walmartlabs/lacinia/async_test.clj

This adds a field resolver decorator whose purpose is to wrap functions that return a core.async channel so that they return a ResolverResult.
I also fixed up some documentation, and renamed the library to lacinia-pedestal.

Add core.async support for field resolver functions

---

README.md

This PR corrects the namespace in the README.md (#9) and adds a quick example server + curl to the usage section.

Correct namespace in README.md and add example usage

---

dev-resources/com/walmartlabs/lacinia/test_utils.clj
docs/subscriptions.rst
src/com/walmartlabs/lacinia/pedestal/interceptors.clj
src/com/walmartlabs/lacinia/pedestal/subscriptions.clj
test/com/walmartlabs/lacinia/pedestal/subscription_interceptors_test.clj
test/com/walmartlabs/lacinia/pedestal/subscriptions_test.clj

Since the functions for creating the default interceptors are public, it is simpler to just allow passing a seq of interceptors, rather than a function that modifies the map of default interceptors.

Minor simplifications to the subscriptions options

---

dev-resources/com/walmartlabs/lacinia/test_utils.clj
docs/response.rst
docs/subscriptions.rst
project.clj
src/com/walmartlabs/lacinia/pedestal.clj
test/com/walmartlabs/lacinia/pedestal_test.clj

This now covers all errors, even before the query is parsed, prepared, and executed.
I also added a missing test related to disallow-subscriptions, and found a bug in the interceptor, also fixed.

Ensure that errors are in the regular format defined by the spec

---

dev-resources/com/walmartlabs/lacinia/test_utils.clj
src/com/walmartlabs/lacinia/pedestal.clj
test/com/walmartlabs/lacinia/parse_test.clj

Before content-type header was not parsed and so requests with encoding parameter, were discarded as having faulty content-type.
This PR implements parser for content-type (from Aleph-project) and changes multimethods to use keywords instead of strings.
Fixes #18

Fix content-type charset parsing

---

docs/_examples/basic-setup.edn

1.) com.walmartlabs.lacinia.util was not required
2.) function call on hello-schema fails because it is not a function

Corrections to the basic example setup code

---

CHANGELOG.md
project.clj
src/com/walmartlabs/lacinia/pedestal/interceptors.clj
test/com/walmartlabs/lacinia/pedestal/interceptors_test.clj

It is sometimes desirable to replace an interceptor with a new interceptor that has its own dependencies (on other interceptors) BUT an overall pipeline often relies on transitive dependencies for proper ordering.
`splice` is pretty much a smarter version of `assoc` for a dependency map, that merges the dependencies of the original and replacement interceptors.  It also checks that the replaced interceptor actually exists.

New function: splice - injects an interceptor w/o affecting existing interceptor's dependencies

---

CHANGELOG.md
README.md
dev-resources/com/walmartlabs/lacinia/test_utils.clj
project.clj
src/com/walmartlabs/lacinia/pedestal.clj
src/com/walmartlabs/lacinia/pedestal/subscriptions.clj
test/com/walmartlabs/lacinia/indirect_schema_test.clj
test/com/walmartlabs/lacinia/pedestal/subscription_interceptors_test.clj
test/com/walmartlabs/lacinia/pedestal/subscriptions_test.clj

This has been requested internally and externally: allow the schema to be updated without a server restart, for REPL-oriented development.
A large chunk of this was refactoring so that the subscriptions test code could be reused for the (trival) case where the compiled schema for a subscription was indirect.

Allow compiled schema to be provided indirectly, as a function that returns the schema

---

CHANGELOG.md
README.md
dev-resources/com/walmartlabs/lacinia/test_utils.clj
docs/_examples/basic-setup.edn
docs/_static/css/custom.css
docs/overview.rst
docs/subscriptions.rst
project.clj
resources/graphiql/package-lock.json
src/com/walmartlabs/lacinia/pedestal.clj
test/com/walmartlabs/lacinia/pedestal_graphiql_disabled_test.clj

This came up in discussion on the Pedestal slack.  Having `pedestal-service` create the server makes it awkward to add additional routing or other configuration before creating the server.

Make it responsibility of caller to invoke io.pedestal.http/create-server

---

src/com/walmartlabs/lacinia/pedestal/subscriptions.clj

Hi,
This typo means that if you perform an operation over the websocket (e.g. a query, or a mutation) the app context doesn't get injected. Fixing it means the app-context is injected properly.
Cheers,
Oliy

Fixing typo in app context getter for execute-operation

---

project.clj
src/com/walmartlabs/lacinia/pedestal/subscriptions.clj
test/com/walmartlabs/lacinia/pedestal/subscriptions_test.clj

Follow the Apollo spec better
Simplify, and make it easier to expose the underlying error map
This also avoids a problem where an exception with a nil message could cause a cascade exception.

Report parse/validation exceptions in subscription requests

---

src/com/walmartlabs/lacinia/pedestal.clj

This just adds documentation for the `:app-context` option key to the `(service-map)` docstring. It's already present in another few places, but I think repeating it here will make it a little more obvious about how to add it in relative to the example code in the docs and README.md.

Adding app-context for service-map docstring

---

src/com/walmartlabs/lacinia/pedestal/subscriptions.clj
test/com/walmartlabs/lacinia/pedestal/subscription_interceptors_test.clj

Hello,
This is related to previous PR #41 and allows the `init-context` function (and indeed any other interceptors) to set data in the `:request` map in the context without it being wiped out by lacinia.
This enables re-use of common pedestal interceptors which do things with the `:request` data.
Thanks for all your work on Lacinia!

Merge the existing request data with that generated by previous interceptors / init-context fn

---

CHANGELOG.md
dev-resources/demo.clj
resources/com/walmartlabs/lacinia/pedestal/graphiql.html
src/com/walmartlabs/lacinia/pedestal.clj

This entirely removes the :api-key option, and replaces it with the new, more general, :ide-headers options.
It also exposes a new function for building and returning the GraphiQL IDE as a Ring response, needed when building customized access to the IDE (for example, to ensure an API key is in the header).

Replace API key support with more flexible IDE headers

---

CHANGELOG.md
project.clj
src/com/walmartlabs/lacinia/pedestal.clj
src/com/walmartlabs/lacinia/pedestal/interceptors.clj
src/com/walmartlabs/lacinia/pedestal/subscriptions.clj
test/com/walmartlabs/lacinia/pedestal_test.clj

In the process of upgrading our internal applications to lacina-pedestal 0.6.0, I found the dependency-based approach for interceptors to be over-engineered and confusing.
Generally, I've found that you simply add a  new interceptor before or after another interceptor, starting from the known and expected ordering.
In practice, the dependency ordering logic got in the way, leading to fragile and confusing code to get the desired new interceptor into the right position.
So mea culpa; this PR is about deprecating that for a release, and switching the logic around so that the normal path is to operate on a vector (or seq) of interceptors.
The new inject function is used to add new interceptors to the vector with a position relative to an existing interceptor (either immediately before or …

Deprecate and replace com.walmartlabs.lacinia.pedestal.interceptors

---

src/com/walmartlabs/lacinia/pedestal.clj
test/com/walmartlabs/lacinia/pedestal_test.clj

The logic for generating GraphQL routes from a compiled schema was not quite right when the :interceptor option was  a seq (the new approach) and not a map (the old and deprecated approach), which caused the routes to be ordered incorrectly

Properly handle interceptor seq

---

src/com/walmartlabs/lacinia/pedestal/subscriptions.clj
test/com/walmartlabs/lacinia/pedestal/subscriptions_test.clj

Hi,
I originally thought that deduplication of subscriptions (two `start` messages with the same id) could or should be the responsibility of the application code. I implemented it in my own code and tried it out, but I observed that although I could avoid launching a new streamer thread, the original streamer thread never got cleaned up.
This is because the `(assoc subs id ...)` was running before the subscription interceptors so it was already too late by the time it hit my deduplication code - the cleanup function to be run on `stop` had been replaced and there was no handle for the original streamer cleanup function anymore.
This change detects duplicates and ignores them, ensuring that any streamer threads launched by this loop will also be cleaned up by this loop when the …

Ignore duplicate subscriptions

---

dev-resources/com/walmartlabs/lacinia/test_utils.clj
src/com/walmartlabs/lacinia/pedestal/subscriptions.clj
test/com/walmartlabs/lacinia/pedestal/subscriptions_test.clj

Based on this initial proposal: https://github.com/walmartlabs/lacinia-pedestal/pull/26
I mainly applied code review's feedback, the only difference with original PR is that I propose we don't merge `context` with the given payload, but to attach the payload on `:connection-params` key instead.

Attach connection init payload to streamer context

---

CHANGELOG.md
src/com/walmartlabs/lacinia/pedestal/subscriptions.clj
test/com/walmartlabs/lacinia/pedestal/subscriptions_test.clj

Users of the library have complained that a very busy streamer can saturate the server, sending responses to clients. This change documents the data flow, and allows the three principle channels in the flow to be configured as desired (e.g, using a lossy buffer, perhaps).

Add new options to control the creation of channels related to subscriptions

---

resources/com/walmartlabs/lacinia/pedestal/graphiql.html

Large queries fail with a "Request Header Fields Too Large" error. 
Setting this header omits including the encoded graphql query in the referrer header.

Set no-referrer header on queries

---

src/com/walmartlabs/lacinia/pedestal.clj

Previously, Lacinia would error with spec instrumentation on when attempting to use port zero to have the OS allocate an available port number.
Getting a randomly assigned port is useful when you want to parallelize your test suite.

Relax specs to enable passing zero as HTTP port

---

src/com/walmartlabs/lacinia/pedestal.clj
src/com/walmartlabs/lacinia/pedestal/spec.clj
src/com/walmartlabs/lacinia/pedestal/subscriptions.clj

A couple of 1.9-only functions (boolean?, pos-int?) snuck in; change the code to get them from clojure-future on 1.8.
Fixes #81

Make use of clojure-future-spec backfill functions to ensure Clojure 1.8 compatibility

---

src/com/walmartlabs/lacinia/pedestal.clj

I've found a typo in the docstring of `com.walmartlabs.lacinia.pedestal/prepare-query-interceptor`.
cf. https://walmartlabs.github.io/apidocs/lacinia-pedestal/com.walmartlabs.lacinia.pedestal.html#var-prepare-query-interceptor

Fix typo in docstring

---

docs/index.rst
docs/interceptors.rst

As discussed in #graphql of Clojurians Slack. This is an example to add extra data to the Lacinia app-context. 
Might not be the best way because in the [`inject-app-context-interceptor doc`](https://walmartlabs.github.io/apidocs/lacinia-pedestal/com.walmartlabs.lacinia.pedestal.html#var-inject-app-context-interceptor) it is stated that the `::pedestal/inject-app-context` can be replaced fully, but we did not manage to make that work.

Example to add data to Lacinia's app-context

---

src/com/walmartlabs/lacinia/pedestal.clj
test/com/walmartlabs/lacinia/pedestal_test.clj

This is less cumbersome than `(remove #(= (:name %) xyz) interceptors)`, ensures the result is a vector (important!), works well in a `->` chain, and keeps the checking that the name could be found.

Enable inject function to remove an interceptor

---

.joker
CHANGELOG.md
README.md
dev-resources/com/walmartlabs/lacinia/test_utils.clj
dev-resources/logback.xml
project.clj
resources/com/walmartlabs/lacinia/pedestal/graphiql.html
resources/graphiql/package-lock.json
src/com/walmartlabs/lacinia/pedestal.clj
src/com/walmartlabs/lacinia/pedestal/internal.clj
src/com/walmartlabs/lacinia/pedestal/subscriptions.clj
src/com/walmartlabs/lacinia/pedestal2.clj
test/com/walmartlabs/lacinia/indirect_schema_test.clj
test/com/walmartlabs/lacinia/parse_test.clj
test/com/walmartlabs/lacinia/pedestal/subscription_interceptors_test.clj
test/com/walmartlabs/lacinia/pedestal/subscriptions_test.clj
test/com/walmartlabs/lacinia/pedestal2_test.clj

I decided that I wanted a "complete set" of interceptors in the new namespace, since you often need to reference them by fully qualified name when injecting new interceptors into the stack; it makes sense to me that if you use `pedestal2/default-interceptors` the interceptors are (except for the one) in the `pedestal2` namespace.

Add new pedestal2 namespace to simplify complex routing

---

dev-resources/com/walmartlabs/lacinia/test_utils.clj
src/com/walmartlabs/lacinia/pedestal.clj
src/com/walmartlabs/lacinia/pedestal/internal.clj
src/com/walmartlabs/lacinia/pedestal2.clj
test/com/walmartlabs/lacinia/pedestal2_test.clj
test/com/walmartlabs/lacinia/pedestal_async_error_test.clj
test/com/walmartlabs/lacinia/pedestal_error_test.clj
test/com/walmartlabs/lacinia/pedestal_test.clj

This change enables the use of standard pedestal error handling for errors raised in the interceptor stack or in lacinia itself. It does so by moving error response generation to the very end of the (outbound) interceptor stack. End users can then inject interceptors prior to it to handle or log exceptions as desired.
As it stands, this is only applicable to the synchronous query executor. I would also like to invoke the same error interceptors with exceptions occurring on the asynchronous path, but am currently unable to figure out how exceptions occurring in channels should be handled in pedestal.
If we do figure that out, we can simplify some of the code here as there are now two error paths (one for sync, one for async).
Besides fixing the asynchronous error handling case, it may also …

Add ability for interceptors to handle exceptions in lacinia

---

CHANGELOG.md
docs/Makefile
docs/conf.py
docs/index.rst
docs/tracing.rst
project.clj
src/com/walmartlabs/lacinia/pedestal.clj
src/com/walmartlabs/lacinia/pedestal/internal.clj
src/com/walmartlabs/lacinia/pedestal2.clj
test/com/walmartlabs/lacinia/pedestal2_test.clj

Because request tracing is somewhat expensive, it is optional, enabled by the `lacinia-tracing` request header; even so it should be disabled entirely in production.

Add support for request tracing

---

src/com/walmartlabs/lacinia/pedestal.clj
src/com/walmartlabs/lacinia/pedestal2.clj

Hello @hlship , thanks for the great library.
My current projects run inside a `docker` container and I faced an issue with an upstream change in pedestal (https://github.com/pedestal/pedestal/issues/604). I noticed that I was not able to pass forward the necessary parameter to apply the fix to my current setup.
The PR contains the necessary extension to keep the library compatible with pedestal standard (default to localhost) but provides the user the ability to change it.
Thanks.

adding the option to change the default host address used by pedestal

---

CHANGELOG.md
project.clj
resources/graphiql/package-lock.json
resources/graphiql/package.json
src/com/walmartlabs/lacinia/pedestal.clj
src/com/walmartlabs/lacinia/pedestal/interceptors.clj
src/com/walmartlabs/lacinia/pedestal/internal.clj
src/com/walmartlabs/lacinia/pedestal/subscriptions.clj
src/com/walmartlabs/lacinia/pedestal2.clj

Pedestal's default [top-level exception handler](https://github.com/pedestal/pedestal/blob/aa71a3a630dd21861c0682eeeebec762cbf3f85c/service/src/io/pedestal/http/impl/servlet_interceptor.clj#L236) logs the entire Pedestal context; this is problematic with lacinia-pedestal, as the entire GraphQL query is inside the context, with numerous references to different parts of the compiled schema; logging this can be hundreds of kilobytes of output.
This PR ensures that, on exit (either normally, via the :leave callback, or via the :error callback) the values added to the context are removed, ensuring that the Pedestal context is (reasonably) clean by the time the top-level error reporting logic is hit.
This is important even in cases where the exception occurs outside of lacinia-pedestal, such as …

Remove keys from the context on exit (leave or error)

---

resources/graphiql/package-lock.json
resources/graphiql/package.json

Start the server with the following command with the current package configuration,
execute the following query at `localhost: 8888 / ui`
```
subscription Tick {
ticks {
count
}
}
```
The following error occurs
```
{
"message": "subscriptionsClient.subscribe is not a function",
"stack": "TypeError: subscriptionsClient.subscribe is not a function \ n at Object.subscribe (http: // localhost: 8888 / assets / graphiql / graphiql-subscriptions-fetcher-browser-client.js: 8734: 64) \ n at http: // localhost: 8888 / assets / graphiql / graphiql.min.js: 1:553273 "
}
```
To fix this, change the version of "subscriptions-transport-ws" to "0.8.x".
Since "subscriptions-transport-ws" is not well maintained, it is better to use "graphql-ws" instead.
https://github.com/enisdenjo/graphql-ws

Fixed "subscriptionsClient.subscribe is not a function"

---

src/com/walmartlabs/lacinia/pedestal/subscriptions.clj

lacinia-pedestal will send a keep alive every 30s, but Jetty also expects a message being sent every 30s. This causes a race, sometimes the go-loop sending the keep alives is fast enough, satisfying Jetty, sometimes Jetty closes the socket just before this keep alive is sent.
Therefore the default keep alive timeout is set to 25s, and a warning is added to the docstring that values at-or-over 30s can cause issues.
-----
Alternatively I've considered configuring Jetty's timeout based on the keep alive timeout, for example by doubling it. But this seems unsupported by pedestal's jetty integration layer.

Subscriptions: Decrease default ka timeout to be less than jettys ws timeout

---

CHANGELOG.md
README.md
deps.edn
dev-resources/com/walmartlabs/lacinia/test_utils.clj
project.clj
src/com/walmartlabs/lacinia/pedestal/subscriptions.clj
test/com/walmartlabs/lacinia/pedestal/subscriptions_test.clj

In Lacinia 1.0, a ResolverResult was handled inside lacinia proper, even though this was not documented; in Lacinia 1.1, this is no longer supported directly, and implementations of subscriptions are responsible.
In addition, in testing, I found a bug where a subscription that passes a value to the callback, then immediately passes a nil, prevents the value from being executed and streamed to the client before the connection is closed; this is fixed, ensuring that all currently executing queries complete and stream before the connection is closed.

Support ResolverResult passed to subscription stream callback

---

.gitignore
build.clj
node/package-lock.json
node/package.json
resources/com/walmartlabs/lacinia/pedestal/graphiql.html
src/com/walmartlabs/lacinia/pedestal/internal.clj

Updated the version of `graphiql`. Also, I removed `graphiql-subscriptions-fetcher` from dependencies because it hasn't been maintained for a long time and we can use` graphiql` without using it.
I checked the following with the `demo` schema.
- `query` and` subscription` works.
- Headers in `request-headers` is attached to the request.
- Values in `initial-connection-params` is contained in the` payload` of the `connection_init` message.

Bump up "graphiql" to "1.7.1". Remove "graphiql-subscriptions-fetcher".

---

build.clj
templates/pom.xml

Add `url` and `scm` tags to final `pom` / `jar` file.
It allow developer tools, like IDE's, cljdoc, mvnrepository, to browse from the artifact to the repository.

Add repository info to pom.xml

---

README.md

When I copied the usage guide and ran `lein run`, I got the following error response when executing the example curl request from the readme:
```{"errors":[{"message":"The provided schema has not been compiled."}]}```
WIth the extra `(schema/compile)` step it works as expected
---
Signed-off-by: Jan-Gerke Salomon [jgs.salomon@gmail.com](mailto:jgs.salomon@gmail.com)

docs(readme): add `(schema/compile)` to `hello-schema`

---

.github/workflows/config.yml
CHANGELOG.md
deps.edn
dev-resources/data_readers.clj
dev-resources/logback.xml
dev-resources/user.clj
src/com/walmartlabs/lacinia/pedestal/internal.clj
src/com/walmartlabs/lacinia/pedestal/subscriptions.clj
test/com/walmartlabs/lacinia/pedestal/subscription_interceptors_test.clj

Pedestal 0.7.0 changes how web sockets work, resulting in this major change.  The effect on most applications will be negligible.

Update for Pedestal 0.7.0
